use postqa;
drop table prev_concept_f;
drop table prev_concept_s;
drop table prev_concept_d;
drop table prev_description_f;
drop table prev_description_s;
drop table prev_description_d;
drop table prev_relationship_s;
drop table prev_relationship_d;
drop table prev_relationship_f;
drop table prev_stated_relationship_s;
drop table prev_stated_relationship_d;
drop table prev_stated_relationship_f;
drop table prev_textdefinition_s;
drop table prev_textdefinition_d;
drop table prev_textdefinition_f;
drop table prev_simplerefset_f;
drop table prev_simplerefset_s;
drop table prev_simplerefset_d;
drop table prev_attributevaluerefset_s;
drop table prev_attributevaluerefset_d;
drop table prev_attributevaluerefset_f;
drop table prev_associationrefset_s;
drop table prev_associationrefset_d;
drop table prev_associationrefset_f;
drop table prev_simplemaprefset_s ;
drop table prev_simplemaprefset_f;
drop table prev_simplemaprefset_d;
drop table prev_langrefset_d;
drop table prev_langrefset_s;
drop table prev_langrefset_f;

drop table curr_concept_f;
drop table curr_concept_s;
drop table curr_concept_d;
drop table curr_description_f;
drop table curr_description_s;
drop table curr_description_d;
drop table curr_relationship_s;
drop table curr_relationship_d;
drop table curr_relationship_f;
drop table curr_stated_relationship_s;
drop table curr_stated_relationship_d;
drop table curr_stated_relationship_f;
drop table curr_textdefinition_s;
drop table curr_textdefinition_d;
drop table curr_textdefinition_f;
drop table curr_simplerefset_f;
drop table curr_simplerefset_s;
drop table curr_simplerefset_d;
drop table curr_attributevaluerefset_s;
drop table curr_attributevaluerefset_d;
drop table curr_attributevaluerefset_f;
drop table curr_associationrefset_s;
drop table curr_associationrefset_d;
drop table curr_associationrefset_f;
drop table curr_simplemaprefset_s ;
drop table curr_simplemaprefset_f;
drop table curr_simplemaprefset_d;
drop table curr_langrefset_d;
drop table curr_langrefset_s;
drop table curr_langrefset_f;


drop table qa_report;
drop table qa_result;
drop table qa_run;
